config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/", to: "pages#home", as: "root"

  get "/listings", to: "listings#index", as: "listings"
  get "/listings/new", to: "listings#new", as: "new_listing"
  post "/listings", to: "listings#create"
  get "/listings/:id", to: "listings#show", as: "listing"

  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"

  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :listings, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :platform
  belongs_to :genre
  enum product: { Brand_new: 0, Used: 1 }
  validates :title, :description, :product, :platform_id, :genre_id, :price, :city, :state, :date_of_listing, presence: true
  has_one_attached :picture
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :listings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_listing, only: [:show]
    before_action :set_user_listing, only: [:edit, :update, :destroy]

    def index
        @listings = Listing.all
    end

    def show
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.email,
            line_items: [{
                name: @listing.title,
                description: @listing.description,
                amount: @listing.price * 100,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    listing_id: @listing.id
                }
            },
            success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
            cancel_url: "#{root_url}listings"
    )
        @session_id = session.id
    end

    def new 
        set_products_platforms_genres
        @listing = Listing.new
    end

    def create
        @listing = current_user.listings.create(listing_params)
        if @listing.errors.any?
            set_products_platforms_genres
            render "new"
        else
            redirect_to listings_path
        end
    end

    def edit
        set_products_platforms_genres
    end

    def update
        @listing = Listing.update(params["id"], listing_params)
        if @listing.errors.any?
            set_products_platforms_genres
            render "edit"
        else
            redirect_to listings_path
        end
    end

    def destroy 
        Listing.find(params["id"]).destroy
        redirect_to listings_path
    end

    private

    def set_listing
        @listing = Listing.find(params[:id])
    end

    def set_user_listing
        @listing = current_user.listings.find_by_id(params[:id])

        if @listing == nil
            redirect_to listings_path
        end
    end

    def set_products_platforms_genres
        @products = Listing.products.keys
        @platforms = Platform.all
        @genres = Genre.all
    end

    def listing_params
        params.require(:listing).permit(:title, :description, :product, :platform_id, :genre_id, :price, :city, :state, :date_of_listing, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @listings = Listing.all
    end

    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success

    end

    def webhook
        payment_id= params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        listing_id = payment.metadata.listing_id
        user_id = payment.metadata.user_id

        p "listing id " + listing_id
        p "user id " + user_id

        status 200
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <h1><%= link_to "GAME AU", root_path, class: "navbar-brand" %></h1>
         
          <ul class="nav nav-right">
            <% if user_signed_in? %>
            
              <%= link_to "Create listing", new_listing_path, class: "nav-link nav-item" %>
            
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          
            <% else %>
              <li><%= link_to "login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
   
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<div class="container">
<% if @listing.errors.any? %>
    <ul>
        <% @listing.errors.full_messages.each do |error| %>
            <li> <%= error %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @listing, local: true) do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div>
    <% @products.each do |option| %>
        <%= form.radio_button :product, option %>
        <%= form.label option %> 
    <% end %>
    </div>

    <div>
        <%= form.label :platform_id %>
        <%= form.select(:platform_id, @platforms.map{|b| [b.name, b.id]}) %>
    </div>

    <div>
        <%= form.label :genre_id %>
        <%= form.select(:genre_id, @genres.map{|b| [b.name, b.id]}) %>
    </div>

    <div>
        <%= form.label :price %>
        <%= form.number_field :price, value: @listing.price ? '%.2f' % @listing.price : nil, min: 0, step: 0.01 %>
    </div>

    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>

    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    
    <div>
        <%= form.label :date_of_listing %>
        <%= form.date_field :date_of_listing %>
    </div>

    <div>
        <%= form.label :picture %> <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
    </div>
    
    <div>
        <%= form.submit %>
    </div>

<% end %>
</div>

app/views/listings/edit.html.erb
<div class="container">
    <h1>Edit Listing</h1>
    <%= render "form", listing: @listing, platforms: @platforms, genres: @genres %>
</div>

app/views/listings/index.html.erb
<div class="row">
<% for listing in @listings %>
  <div class="col-md-4">
        <div ="card">
                <img class="card-img-top" style="width: 18rem;"<%= image_tag listing.picture if listing.picture.attached? %>
                <div class="card-body">
                        <h5 class="card-title"> <%= listing.title%> </h5>
                                <p> Product: <%= listing.product.humanize.titleize %></p>
                                <p> Platform: <%= listing.platform.name%></p>
                                <p> Genre: <%= listing.genre.name.titleize %></p>
                                <p> Price: <%= number_to_currency(listing.price)%></p> 
                                <p> Seller: <%= listing.user.email %></p>
                        <button class="btn btn-outline-secondary btn-sm" type="submit"><%= link_to "View Listing", listing_path(listing.id)%></button>
                        <% if current_user.id == listing.user_id %> 
                                <%= form_with model: listing, local: true, method: "delete" do |form| %>
                                <a><%= submit_tag "delete", class: "icon" %></a>
                            <button class="btn btn-outline-secondary btn-sm" type="submit"><%= link_to "Edit", edit_listing_path(listing.id) %></button>
                                <% end %>
                                <% end %>
                </div>  
        </div> 
</div> 
<% end %>   
</span>

app/views/listings/new.html.erb
<div class="container">
    <h1>New Listing</h1>
    <%= render "form", listing: @listing, platforms: @platforms, genres: @genres %>
</div>

app/views/listings/show.html.erb
<div class="container">
  <% if @listing.picture.attached? %>
    <img class="img-thumbnail" <%= image_tag  @listing.picture%>
  <% end %>

  <h1><%= @listing.title %></h1>
  <h2>Description</h2>
    <p> Product: <%= @listing.product.humanize.titleize %></p>
    <p> Platform: <%= @listing.platform.name%></p>
    <p> Genre: <%= @listing.genre.name.titleize %></p>
    <p> Seller: <%= @listing.user.email %></p>



    <button data-stripe="payment">
      Buy <%= number_to_currency(@listing.price) %>
    </button>
  <div>
    <script src="https://js.stripe.com/v3/"></script>

    <script>
      document
        .querySelector("[data-stripe='payment']")
        .addEventListener("click", () => {
          const stripe = Stripe(
            "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
          );

          stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
          });
        });
    </script>
  </div>
  <br>
  <p><%= @listing.description %></p>
</div>

app/views/pages/home.html.erb
<div class="row">
<% for listing in @listings %>
  <div class="col-md-4">
        <div ="card">
        <img class="card-img-top" style="width: 18rem;"<%= image_tag listing.picture if listing.picture.attached? %>
                <div class="card-body">
                        <h5 class="card-title"> <%= listing.title%> </h5>
                                <p> Product: <%= listing.product.humanize.titleize %></p>
                                <p> Platform: <%= listing.platform.name%></p>
                                <p> Genre: <%= listing.genre.name.titleize %></p>
                                <p> Price: <%= number_to_currency(listing.price)%></p> 
                                <p> Seller: <%= listing.user.email %></p>
                        <button class="btn btn-outline-secondary btn-sm" type="submit"><%= link_to "View Listing", listing_path(listing.id)%></button>
                        <% if user_signed_in? && current_user.id == listing.user_id %>
                                <%= form_with model: listing, local: true, method: "delete" do |form| %>
                                <a><%= submit_tag "delete", class: "icon" %></a>
                            <button class="btn btn-outline-secondary btn-sm" type="submit"><%= link_to "Edit", edit_listing_path(listing.id) %></button>
                                <% end %>
                                <% end %>
                </div>  
        </div> 
</div> 
<% end %>   

app/views/payments/success.html.erb
You've successfully made a payment! <%= link_to "Go To Listings", listings_path %>